/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.41
 * Generated at: 2019-03-11 09:38:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Urban Furnish</title>\r\n");
      out.write("<!-- Meta tag Keywords -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Trendy Designs web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web Designs\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!--// Meta tag Keywords -->\r\n");
      out.write("<!-- css files -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\"> <!-- Bootstrap-Core-CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\" /> <!-- Style-CSS --> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.css\"> <!-- Font-Awesome-Icons-CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.css\" type=\"text/css\" media=\"all\"/> <!-- Owl-Carousel-CSS -->\r\n");
      out.write("<!-- pop-up-box -->\r\n");
      out.write("<link href=\"css/popuo-box.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- //pop-up-box -->\r\n");
      out.write("<!-- For-Gallery-CSS -->\r\n");
      out.write("<link href=\"css/viewbox.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- //For-Gallery-CSS -->\r\n");
      out.write("<!-- //css files -->\r\n");
      out.write("<!-- web-fonts -->\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext\" rel=\"stylesheet\">\r\n");
      out.write("<!-- //web-fonts -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main-agile\" id=\"home\">\r\n");
      out.write("\t<!-- header -->\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-4 w3l_header_center\">\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<h1><a class=\"navbar-brand\" href=\"index.html\"><span>URBAN FURNISH</span></a></h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 w3l_header_right w3l-r\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#small-dialog\" class=\"play-icon popup-with-zoom-anim\">Sign In</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"header-bottom\">\r\n");
      out.write("\t\t<!-- navigation section -->\r\n");
      out.write("\t\t<div class=\"w3_navigation\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"navbar-header navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse navbar-collapse navbar-right\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t<nav class=\"menu menu--miranda\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav navbar-nav menu__list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"menu__item\"><a href=\"Home.html\" class=\"menu__link\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"menu__item\"><a href=\"#contact\" class=\"scroll menu__link\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!--  \t\r\n");
      out.write("\t\t\t\t<div class=\"agileinfo_search\">\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"Search\" placeholder=\"Type text here...\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\" \">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t-->\r\n");
      out.write("\t\t\t\t<!--  <div class=\"clearfix\"></div>-->\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /navigation section -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //header -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Slider -->\r\n");
      out.write("<div class=\"slider\">\r\n");
      out.write("\t\t<div class=\"callbacks_container\">\r\n");
      out.write("\t\t\t<ul class=\"rslides\" id=\"slider\">\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3layouts-banner-top w3layouts-banner-top1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"slider-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3layouts-banner-top\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"slider-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3layouts-banner-top w3layouts-banner-top2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"slider-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //Slider -->\t\t\t\t\r\n");
      out.write("<!-- pop-up-box -->\r\n");
      out.write("<div id=\"small-dialog\" class=\"mfp-hide w3ls_small_dialog wthree_pop\">\r\n");
      out.write("\t<h3 class=\"agileinfo_sign\">Sign In</h3>\t\r\n");
      out.write("\t<div class=\"agileits_signin_form\">\r\n");
      out.write("\t\t<form action=\"login\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"email\" name=\"youremail\" placeholder=\"Your Email\" required=\"\">\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"password\" placeholder=\"Password\" required=\"\">\r\n");
      out.write("\t\t\t<div class=\"agile_remember\">\r\n");
      out.write("\t\t\t\t<div class=\"agile_remember_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--  <div class=\"agile_remember_right\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Forgot Password?</a>\r\n");
      out.write("\t\t\t\t</div>-->\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"SIGN IN\">\r\n");
      out.write("\t\t\t<p>Don't have an account <a href=\"#small-dialog1\" class=\"play-icon popup-with-zoom-anim\">Sign Up</a></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"small-dialog1\" class=\"mfp-hide w3ls_small_dialog wthree_pop\">\r\n");
      out.write("\t<h3 class=\"agileinfo_sign\">Sign Up</h3>\t\r\n");
      out.write("\t<div class=\"agileits_signin_form\">\r\n");
      out.write("\t\t<form action=\"register\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"firstname\" placeholder=\"First Name\" required=\"\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"lastname\" placeholder=\"Last Name\" required=\"\">\r\n");
      out.write("\t\t\t<input type=\"email\" name=\"youremail\" placeholder=\"Your Email\" required=\"\">\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"password\" placeholder=\"Password\" required=\"\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"SIGN UP\">\r\n");
      out.write("\t\t\t<p>Already a member <a href=\"#small-dialog\" class=\"play-icon popup-with-zoom-anim\">Sign In</a></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- //welcome -->\r\n");
      out.write("<!-- testimonials -->\r\n");
      out.write("<div class=\"testimonials\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h3 class=\"head head1\">About Urban Furnish</h3>\r\n");
      out.write("\t\t<ul id=\"flexiselDemo1\">\t\t\t\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<div class=\"wthree_testimonials_grid_main\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthree_testimonials_grid\">\r\n");
      out.write("\t\t\t\t\t<p>Urban Furnish offers a unique selection of stylish,contemporary \r\n");
      out.write("  and chic furniture online.Our online furniture range includes         sofas,beds,dinning tables,tv units,wardrobes,dressing tables\r\n");
      out.write("  and lots more.Through this website one can easily select \r\n");
      out.write("  and buy the ones you like,and stay updated about new and \r\n");
      out.write("  contemporary designs.</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wthree_testimonials_grid_pos\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"\" alt=\" \" class=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"wthree_testimonials_grid1\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<div class=\"wthree_testimonials_grid_main\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthree_testimonials_grid\">\r\n");
      out.write("\t\t\t\t\t<p>Furnishing forms a considerable portion of designing a home of your dreams as the walls, the sofa, the wardrobes, and the curtains all form essence of your home. We understand your thought and emotion when you buy any piece of furniture for your home and we strive to deliver you the products that are long lasting, affordable, and fit your needs best\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wthree_testimonials_grid_pos\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"\" alt=\" \" class=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"wthree_testimonials_grid1\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("<li>\r\n");
      out.write("\t\t\t\t<div class=\"wthree_testimonials_grid_main\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthree_testimonials_grid\">\r\n");
      out.write("\t\t\t\t\t<p>Expert advice at your doorstep: After you place your order, our designers will visit you to understand your needs better and offer you their expert advice. Once the product is ready, our experts will install it at your place.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wthree_testimonials_grid_pos\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"\" alt=\" \" class=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"wthree_testimonials_grid1\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<div class=\"wthree_testimonials_grid_main\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthree_testimonials_grid\">\r\n");
      out.write("\t\t\t\t\t<p>Reasonable pricing: As we manufacture furniture to your specific order in our in-house facility and directly deliver it to your home without maintaining any inventory, our prices our 30% lower than the market.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wthree_testimonials_grid_pos\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"\" alt=\" \" class=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"wthree_testimonials_grid1\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //testimonials -->\r\n");
      out.write("<!-- contact -->\r\n");
      out.write("<div class=\"contact_w3agile\" id=\"contact\">\r\n");
      out.write("\t<div class=\"container wow fadeInUp animated animated\" data-wow-delay=\".5s\" style=\"visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;\">\r\n");
      out.write("\t\t<h3 class=\"title-w3\">Contact Us</h3>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"text\" placeholder=\"Name\" name=\"Name\" required=\"\">\r\n");
      out.write("\t\t\t<input type=\"email\" placeholder=\"Email\" name=\"Email\" required=\"\">\r\n");
      out.write("\t\t\t<textarea name=\"Message\" placeholder=\"Message\" required=\"\"></textarea>\r\n");
      out.write("\t\t\t<div class=\"con-form text-center\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Send\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- //contact -->\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"map\" style=\"width: 100%; height: 500px\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction myMap() {\r\n");
      out.write("\t\t\tvar myCenter = new google.maps.LatLng(17.526017455157266,\r\n");
      out.write("\t\t\t\t\t78.37009191513062);\r\n");
      out.write("\t\t\tvar mapCanvas = document.getElementById(\"map\");\r\n");
      out.write("\t\t\tvar mapOptions = {\r\n");
      out.write("\t\t\t\tcenter : myCenter,\r\n");
      out.write("\t\t\t\tzoom : 18\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tvar map = new google.maps.Map(mapCanvas, mapOptions);\r\n");
      out.write("\t\t\tvar marker = new google.maps.Marker({\r\n");
      out.write("\t\t\t\tposition : myCenter\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tmarker.setMap(map);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// Zoom to 9 when clicking on marker\r\n");
      out.write("\t\t\tgoogle.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("\t\t\t\tmap.setZoom(9);\r\n");
      out.write("\t\t\t\tmap.setCenter(marker.getPosition());\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCGAT4Yz6znl6jEBVh1yQ8x6j8q0w6o0c4&callback=myMap\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("\t<!-- //main -->\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<div class=\"foote-w3l\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"col-md-4 ag-w3\">\r\n");
      out.write("\t\t\t<li class=\"dropdown menu__item\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"dropdown-toggle menu__link\"  data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Menu<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#about\" class=\"scroll\">About</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#services\" class=\"scroll\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#gallery\" class=\"scroll\">Gallery</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#contact\" class=\"scroll\">Contact</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-4 ag-w3-3\">\r\n");
      out.write("\t\t\t<a href=\"#home\" class=\"scroll\"><i class=\"fa fa-angle-up\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-4 ag-w3-2\">\r\n");
      out.write("\t\t\t<i class=\"fa fa-phone\" aria-hidden=\"true\"></i><span> 040 4241 7773</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"footer w3ls\">\r\n");
      out.write("\t<div class=\"footer-2 w3ls\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"footer-main\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-top\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 ftr-grid fg2\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Our Address</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ftr-address\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"local\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ftr-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Bvrit Hyderabad</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ftr-address\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"local\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-phone\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ftr-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p> 040 4241 7773</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ftr-address\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"local\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 w3l_header_left-2\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ftr-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href=\"mailto:bvrithyderabad@edu.in\">bvrithyderabad@edu.in</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 ftr-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"logo-fo\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2><a href=\"index.html\">URBAN FURNISH</a></h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"copyrights\">\r\n");
      out.write("\t\t<p>&copy; 2018 Urban Furnish. All rights reserved |</a></p>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //Footer -->\r\n");
      out.write("<!-- js-scripts -->\t\t\t\t\t\r\n");
      out.write("<!-- js -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap.js\"></script> <!-- Necessary-JavaScript-File-For-Bootstrap --> \r\n");
      out.write("<!-- //js -->\t\r\n");
      out.write("<!-- Baneer-js -->\r\n");
      out.write("\t<script src=\"js/responsiveslides.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function () {\r\n");
      out.write("\t\t\t$(\"#slider\").responsiveSlides({\r\n");
      out.write("\t\t\t\tauto: true,\r\n");
      out.write("\t\t\t\tpager:false,\r\n");
      out.write("\t\t\t\tnav: true,\r\n");
      out.write("\t\t\t\tspeed: 1000,\r\n");
      out.write("\t\t\t\tnamespace: \"callbacks\",\r\n");
      out.write("\t\t\t\tbefore: function () {\r\n");
      out.write("\t\t\t\t\t$('.events').append(\"<li>before event fired.</li>\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tafter: function () {\r\n");
      out.write("\t\t\t\t\t$('.events').append(\"<li>after event fired.</li>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //Baneer-js -->\r\n");
      out.write("<!-- Popup-js -->\r\n");
      out.write("\t\t<script src=\"js/jquery.magnific-popup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t$('.popup-with-zoom-anim').magnificPopup({\r\n");
      out.write("\t\ttype: 'inline',\r\n");
      out.write("\t\tfixedContentPos: false,\r\n");
      out.write("\t\tfixedBgPos: true,\r\n");
      out.write("\t\toverflowY: 'auto',\r\n");
      out.write("\t\tcloseBtnInside: true,\r\n");
      out.write("\t\tpreloader: false,\r\n");
      out.write("\t\tmidClick: true,\r\n");
      out.write("\t\tremovalDelay: 300,\r\n");
      out.write("\t\tmainClass: 'my-mfp-zoom-in'\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //Popup-js -->\r\n");
      out.write("<!-- Owl-Carousel-JavaScript -->\r\n");
      out.write("<script src=\"js/owl.carousel.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#owl-demo\").owlCarousel ({\r\n");
      out.write("\t\t\titems : 3,\r\n");
      out.write("\t\t\tlazyLoad : true,\r\n");
      out.write("\t\t\tautoPlay : true,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //Owl-Carousel-JavaScript -->  \r\n");
      out.write("<!-- For-Gallery-js -->\r\n");
      out.write("<script src=\"js/jquery.viewbox.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('.thumbnail').viewbox();\r\n");
      out.write("\t\t\t$('.thumbnail-2').viewbox();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t(function(){\r\n");
      out.write("\t\t\t\tvar vb = $('.popup-link').viewbox();\r\n");
      out.write("\t\t\t\t$('.popup-open-button').click(function(){\r\n");
      out.write("\t\t\t\t\tvb.trigger('viewbox.open');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$('.close-button').click(function(){\r\n");
      out.write("\t\t\t\t\tvb.trigger('viewbox.close');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t})();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t(function(){\r\n");
      out.write("\t\t\t\tvar vb = $('.popup-steps').viewbox({navButtons:false});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('.steps-button').click(function(){\r\n");
      out.write("\t\t\t\t\tvb.trigger('viewbox.open',[0]);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('.next-button').click(function(){\r\n");
      out.write("\t\t\t\t\tvb.trigger('viewbox.open',[1]);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$('.prev-button').click(function(){\r\n");
      out.write("\t\t\t\t\tvb.trigger('viewbox.open',[0]);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$('.ok-button').click(function(){\r\n");
      out.write("\t\t\t\t\tvb.trigger('viewbox.close');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t})();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //For-Gallery-js -->\r\n");
      out.write("<!-- Flexslider-js for-testimonials -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t$(window).load(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#flexiselDemo1\").flexisel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvisibleItems:1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tanimationSpeed: 1000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautoPlay: false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautoPlaySpeed: 3000,    \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpauseOnHover: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tenableResponsiveBreakpoints: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresponsiveBreakpoints: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tportrait: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:480,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 1\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlandscape: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:640,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems:1\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttablet: { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePoint:768,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvisibleItems: 1\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\" src=\"js/jquery.flexisel.js\"></script>\r\n");
      out.write("<!-- //Flexslider-js for-testimonials -->\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<!-- //js-scripts -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
