/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.41
 * Generated at: 2019-03-15 13:17:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;

public final class vieworders_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>URBAN FURNISH</title>\r\n");
      out.write("<!-- Meta tag Keywords -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"Trendy Designs web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web Designs\" />\r\n");
      out.write("<script type=\"application/x-javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("function hideURLbar(){ window.scrollTo(0,1); } \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!--// Meta tag Keywords -->\r\n");
      out.write("<!-- css files -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<!-- Bootstrap-Core-CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- Style-CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.css\">\r\n");
      out.write("<!-- Font-Awesome-Icons-CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.css\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<!-- Owl-Carousel-CSS -->\r\n");
      out.write("<!-- pop-up-box -->\r\n");
      out.write("<link href=\"css/popuo-box.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<!-- //pop-up-box -->\r\n");
      out.write("<!-- For-Gallery-CSS -->\r\n");
      out.write("<link href=\"css/viewbox.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<!-- //For-Gallery-CSS -->\r\n");
      out.write("<!-- //css files -->\r\n");
      out.write("<!-- web-fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- //web-fonts -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"main-agile\" id=\"home\">\r\n");
      out.write("\t\t<!-- header -->\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 w3l_header_center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navbar-brand\" href=\"index.html\"><span>URBAN\r\n");
      out.write("\t\t\t\t\t\t\t\t\tFURNISH</span></a>\r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 w3l_header_right w3l-r\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"Upload.jsp\">Uploading a Product</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"adminwelcome.jsp\">View Products</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"adminlogin.html\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");

String id = request.getParameter("userId");
String driverName = "com.mysql.jdbc.Driver";
String connectionUrl = "jdbc:mysql://localhost:3306/";
String dbName = "urban_furnish";
String userId = "root";
String password = "root";

try {
Class.forName(driverName);
} catch (ClassNotFoundException e) {
e.printStackTrace();
}
Blob image = null;
byte[ ] imgData = null ;
Connection connection = null;
Statement statement = null;
ResultSet resultSet = null;

      out.write("\r\n");
      out.write("<h2 align=\"center\"><font><strong>Orders List</strong></font></h2>\r\n");
      out.write("<table align=\"center\" cellpadding=\"5\" cellspacing=\"60\" border=\"3\">\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr bgcolor=\"black\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td><font size=\"5\" color=\"white\">firstname </font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"white\">lastname  </font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"white\">email  </font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"white\">phone number </font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"white\">address </font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"white\">city </font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"white\">zip code </font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"white\">state </font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"white\">product_name </font></td>\r\n");
      out.write("</tr>\r\n");

try{ 
connection = DriverManager.getConnection(connectionUrl+dbName, userId, password);
statement=connection.createStatement();
String sql ="SELECT * FROM orders1";
resultSet = statement.executeQuery(sql);

while(resultSet.next()){
	//image = resultSet.getBlob(1);
	//imgData = image.getBytes(1,(int)image.length());
	PrintWriter ot = response.getWriter();
	//ot.println(imgData);
	



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr bgcolor=\"white\">\r\n");
      out.write("\r\n");
      out.write("<td><font size=\"5\" color=\"black\">");
      out.print(resultSet.getString("firstname") );
      out.write("</font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"black\">");
      out.print(resultSet.getString("lastname") );
      out.write("</font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"black\">");
      out.print(resultSet.getString("email") );
      out.write("</font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"black\">");
      out.print(resultSet.getString("phonenumber"));
      out.write("</font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"black\">");
      out.print(resultSet.getString("address"));
      out.write("</font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"black\">");
      out.print(resultSet.getString("city"));
      out.write("</font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"black\">");
      out.print(resultSet.getString("zipcode"));
      out.write("</font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"black\">");
      out.print(resultSet.getString("state"));
      out.write("</font></td>\r\n");
      out.write("<td><font size=\"5\" color=\"black\">");
      out.print(resultSet.getString("product_name") );
      out.write("</font></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
 
}
}
 catch (Exception e) {
e.printStackTrace();
}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t// Get the modal\r\n");
      out.write("\t\t\tvar modal = document.getElementById('id01');\r\n");
      out.write("\r\n");
      out.write("\t\t\t// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("\t\t\twindow.onclick = function(event) {\r\n");
      out.write("\t\t\t\tif (event.target == modal) {\r\n");
      out.write("\t\t\t\t\tmodal.style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- js-scripts -->\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\r\n");
      out.write("<!-- Necessary-JavaScript-File-For-Bootstrap -->\r\n");
      out.write("<!-- //js -->\r\n");
      out.write("<!-- Baneer-js -->\r\n");
      out.write("<script src=\"js/responsiveslides.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#slider\").responsiveSlides({\r\n");
      out.write("\t\t\tauto : true,\r\n");
      out.write("\t\t\tpager : false,\r\n");
      out.write("\t\t\tnav : true,\r\n");
      out.write("\t\t\tspeed : 1000,\r\n");
      out.write("\t\t\tnamespace : \"callbacks\",\r\n");
      out.write("\t\t\tbefore : function() {\r\n");
      out.write("\t\t\t\t$('.events').append(\"<li>before event fired.</li>\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tafter : function() {\r\n");
      out.write("\t\t\t\t$('.events').append(\"<li>after event fired.</li>\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //Baneer-js -->\r\n");
      out.write("<!-- Popup-js -->\r\n");
      out.write("<script src=\"js/jquery.magnific-popup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('.popup-with-zoom-anim').magnificPopup({\r\n");
      out.write("\t\t\ttype : 'inline',\r\n");
      out.write("\t\t\tfixedContentPos : false,\r\n");
      out.write("\t\t\tfixedBgPos : true,\r\n");
      out.write("\t\t\toverflowY : 'auto',\r\n");
      out.write("\t\t\tcloseBtnInside : true,\r\n");
      out.write("\t\t\tpreloader : false,\r\n");
      out.write("\t\t\tmidClick : true,\r\n");
      out.write("\t\t\tremovalDelay : 300,\r\n");
      out.write("\t\t\tmainClass : 'my-mfp-zoom-in'\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //Popup-js -->\r\n");
      out.write("<!-- Owl-Carousel-JavaScript -->\r\n");
      out.write("<script src=\"js/owl.carousel.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#owl-demo\").owlCarousel({\r\n");
      out.write("\t\t\titems : 3,\r\n");
      out.write("\t\t\tlazyLoad : true,\r\n");
      out.write("\t\t\tautoPlay : true,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //Owl-Carousel-JavaScript -->\r\n");
      out.write("<!-- For-Gallery-js -->\r\n");
      out.write("<script src=\"js/jquery.viewbox.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$('.thumbnail').viewbox();\r\n");
      out.write("\t\t$('.thumbnail-2').viewbox();\r\n");
      out.write("\r\n");
      out.write("\t\t(function() {\r\n");
      out.write("\t\t\tvar vb = $('.popup-link').viewbox();\r\n");
      out.write("\t\t\t$('.popup-open-button').click(function() {\r\n");
      out.write("\t\t\t\tvb.trigger('viewbox.open');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('.close-button').click(function() {\r\n");
      out.write("\t\t\t\tvb.trigger('viewbox.close');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t})();\r\n");
      out.write("\r\n");
      out.write("\t\t(function() {\r\n");
      out.write("\t\t\tvar vb = $('.popup-steps').viewbox({\r\n");
      out.write("\t\t\t\tnavButtons : false\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('.steps-button').click(function() {\r\n");
      out.write("\t\t\t\tvb.trigger('viewbox.open', [ 0 ]);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('.next-button').click(function() {\r\n");
      out.write("\t\t\t\tvb.trigger('viewbox.open', [ 1 ]);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('.prev-button').click(function() {\r\n");
      out.write("\t\t\t\tvb.trigger('viewbox.open', [ 0 ]);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('.ok-button').click(function() {\r\n");
      out.write("\t\t\t\tvb.trigger('viewbox.close');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t})();\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //For-Gallery-js -->\r\n");
      out.write("<!-- Flexslider-js for-testimonials -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(window).load(function() {\r\n");
      out.write("\t\t$(\"#flexiselDemo1\").flexisel({\r\n");
      out.write("\t\t\tvisibleItems : 1,\r\n");
      out.write("\t\t\tanimationSpeed : 1000,\r\n");
      out.write("\t\t\tautoPlay : false,\r\n");
      out.write("\t\t\tautoPlaySpeed : 3000,\r\n");
      out.write("\t\t\tpauseOnHover : true,\r\n");
      out.write("\t\t\tenableResponsiveBreakpoints : true,\r\n");
      out.write("\t\t\tresponsiveBreakpoints : {\r\n");
      out.write("\t\t\t\tportrait : {\r\n");
      out.write("\t\t\t\t\tchangePoint : 480,\r\n");
      out.write("\t\t\t\t\tvisibleItems : 1\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tlandscape : {\r\n");
      out.write("\t\t\t\t\tchangePoint : 640,\r\n");
      out.write("\t\t\t\t\tvisibleItems : 1\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\ttablet : {\r\n");
      out.write("\t\t\t\t\tchangePoint : 768,\r\n");
      out.write("\t\t\t\t\tvisibleItems : 1\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.flexisel.js\"></script>\r\n");
      out.write("<!-- //Flexslider-js for-testimonials -->\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event) {\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({\r\n");
      out.write("\t\t\t\tscrollTop : $(this.hash).offset().top\r\n");
      out.write("\t\t\t}, 1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<!-- //js-scripts -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
